[package]
name = "quip"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
slint = "1.8.0"
nix = "0.30.1"
config = "0.15.11"
evdev-rs = "0.6.1"

[build-dependencies]
slint-build = "1.8.0"
